- name: Create virtual environment directory as {{ app_user }}
  file:
    state: directory
    recurse: yes
    mode: 0700
    owner: "{{ app_user }}"
    path: "{{ python_venv_base }}"

- name: Upgrade pip, setuptools, and wheels (virtual environment)
  pip:
    name:
      - pip
      - setuptools
      - wheel
    umask: "0022"
    virtualenv: "{{ python_venv_name }}"
    virtualenv_site_packages: yes
    state: latest
  become_user: "{{ app_user }}"

- name: Install required Python packages into virtual environment
  pip:
    name:
      - anndata
      - biocode
      - biopython
      - dash-bio
      - dash
      - Flask
      - Flask-Compress
      - Flask-RESTful
      - h5py
      - jupyter
      - kaleido
      - louvain
      # - MulticoreTSNE
      - git+https://github.com/DmitryUlyanov/Multicore-TSNE.git@master
      - diffxpy
      - mysql-connector-python
      - numba
      - Pillow
      - plotly
      - python-dotenv
      - requests
      - scanpy
      - SQLAlchemy
      - xlrd
    umask: "0022"
    virtualenv: "{{ python_venv_name }}"
  become_user: "{{ app_user }}"