---
# This playbook deploys the gEAR/DHART LAMP stack on the host server
# Install required libraries, configure and deploy the webserver
# and aplication code, deploy MySQL and configure the database

# change hosts to the target host server
- name: Deploy the gEAR/DHART LAMP stack on the host server
  hosts: "{{ target_host }}"
  roles:
    - {role: "setup_var_www", tags: "setup_var_www"}
    - {role: "install", tags: "install"}
    - {role: "setup_venv", tags: "setup_venv"}
    - {role: "configure_database", tags: "configure_database"}
    - {role: "configure_dhart", tags: "configure_dhart"}
    - {role: "load_external_data", tags: "load_external_data"}
    - {role: "configure_web_server", tags: "configure_web_server"}
