- name: Create gear.ini
  ansible.builtin.template:
    src: gear.ini.j2
    dest: "{{ gear_repo_dir }}/gear.ini"
    owner: "{{ app_user }}"
    group: "{{ app_group }}"
  notify: Restart Apache

- name: Install cron job
  ansible.builtin.template:
    src: cron.j2
    dest: /etc/cron.d/dhart

- name: Create logo image (normal)
  ansible.builtin.copy:
    src: logo-main-normal_framed.png
    dest: "{{ gear_repo_dir }}/www/img/by_domain/dhart/logo-main-normal.png"
    owner: "{{ app_user }}"
    group: "{{ app_group }}"

- name: Create logo image (small) - try to get away with the normal logo for now
  ansible.builtin.copy:
    src: logo-main-normal_framed.png
    dest: "{{ gear_repo_dir }}/www/img/by_domain/dhart/logo-main-small.png"
    owner: "{{ app_user }}"
    group: "{{ app_group }}"

- name: Fix www/site_domain_prefs.json
  ansible.builtin.lineinfile:
    path: "{{ gear_repo_dir }}/www/site_domain_prefs.json"
    regexp: '"domain_url":'
    line: "    \"domain_url\": \"{{ domain_url }}\","